# Generated by Django 2.0.5 on 2019-07-12 12:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('levels_set', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='criteria_catalog_disp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_crit_display_order', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, null=True, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='exp_defaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='exp_fLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpCriteriaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cOrder_id', models.CharField(max_length=10, null=True)),
                ('fvp', models.CharField(max_length=10, null=True)),
                ('position', models.IntegerField(null=True)),
                ('sh_hd', models.IntegerField(null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Block')),
            ],
        ),
        migrations.CreateModel(
            name='experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='DESIGN_MODE', max_length=100)),
                ('custom_exp_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('batches_title', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, default=100, null=True)),
                ('inFile', models.CharField(blank=True, max_length=256, null=True)),
                ('outFile', models.CharField(blank=True, max_length=256, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'experiment',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='experiment_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_levels', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=126, size=6)),
            ],
        ),
        migrations.CreateModel(
            name='exStatusCd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.IntegerField()),
                ('s_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ExpStatusCode',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='mobilephones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('Memory', models.CharField(blank=True, max_length=500, null=True)),
                ('Ram', models.CharField(blank=True, max_length=500, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('Size', models.FloatField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('price_in_usd', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('imagepath1', models.CharField(blank=True, max_length=300, null=True)),
                ('imagepath2', models.CharField(blank=True, max_length=300, null=True)),
                ('battery', models.CharField(max_length=400, null=True)),
                ('backcam', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'mobilephones',
            },
        ),
        migrations.CreateModel(
            name='MobilePhones_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Companny', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('battery', models.CharField(max_length=400, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('Size', models.FloatField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('price_in_usd', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('imagepath1', models.CharField(max_length=300, null=True)),
                ('imagepath2', models.CharField(max_length=300, null=True)),
                ('backcam', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mobile Phones Test',
            },
        ),
        migrations.CreateModel(
            name='PhoneCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('priority', models.CharField(max_length=20, null=True)),
                ('position', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Phone Criteria',
            },
        ),
        migrations.CreateModel(
            name='platform_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_symbol', models.CharField(max_length=3, null=True)),
                ('feature_levels', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=126, null=True, size=6)),
            ],
            options={
                'verbose_name_plural': 'platform_feature',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Role',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='samsung_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Companny', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('Size', models.FloatField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('price_in_pkr', models.IntegerField(null=True)),
                ('price_in_usd', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('imagepath1', models.CharField(max_length=300, null=True)),
                ('imagepath2', models.CharField(max_length=300, null=True)),
                ('battery', models.CharField(max_length=400, null=True)),
                ('back_camera', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'samsungphone',
            },
        ),
        migrations.CreateModel(
            name='selectedAdminPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pset_id', models.CharField(blank=True, max_length=10, null=True)),
                ('p_order', models.IntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Block')),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
                ('mob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.mobilephones')),
            ],
        ),
        migrations.CreateModel(
            name='signup_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300, null=True)),
                ('role', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sort_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField(null=True)),
                ('feature', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(null=True)),
                ('sh_hd', models.IntegerField(null=True)),
                ('exp_sets', models.CharField(max_length=200, null=True)),
                ('roles', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Role')),
            ],
            options={
                'verbose_name_plural': 'Sort Feature',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Block')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='userroles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrole', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userscoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_id', models.IntegerField(null=True)),
                ('element_id', models.IntegerField(null=True)),
                ('feat_priority', models.IntegerField(null=True)),
                ('feat_name', models.CharField(max_length=200, null=True)),
                ('mobile_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('date_modified', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'User Score Record',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experiment_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectedadminphones',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment_feature',
            name='p_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.platform_feature'),
        ),
        migrations.AddField(
            model_name='experiment_feature',
            name='used_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='admin',
            field=models.ManyToManyField(related_name='can_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='status_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.exStatusCd'),
        ),
        migrations.AddField(
            model_name='expcriteriaorder',
            name='exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AddField(
            model_name='expcriteriaorder',
            name='pCriteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.PhoneCriteria'),
        ),
        migrations.AddField(
            model_name='exp_flevel',
            name='e_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment_feature'),
        ),
        migrations.AddField(
            model_name='exp_defaults',
            name='p_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.platform_feature'),
        ),
        migrations.AddField(
            model_name='exp_defaults',
            name='used_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AddField(
            model_name='block',
            name='used_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AddField(
            model_name='batch',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Role'),
        ),
    ]
