# Generated by Django 2.0.5 on 2019-07-12 12:53

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190712_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp_flevel',
            name='used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AddField(
            model_name='platform_feature',
            name='default_levels',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=126, null=True, size=6),
        ),
    ]
