# Generated by Django 2.0.5 on 2018-11-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181030_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='exp_fLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_level', models.CharField(max_length=100)),
                ('e_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment_feature')),
            ],
        ),
    ]
