# Generated by Django 2.0.5 on 2019-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190712_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='exp_fdefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_level', models.CharField(max_length=20)),
                ('d_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.platform_feature')),
                ('used_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
            options={
                'verbose_name_plural': 'Exp Default Feature',
            },
        ),
        migrations.RemoveField(
            model_name='exp_defaults',
            name='p_feature',
        ),
        migrations.RemoveField(
            model_name='exp_defaults',
            name='used_in',
        ),
        migrations.DeleteModel(
            name='exp_defaults',
        ),
    ]
