# Generated by Django 2.0.5 on 2018-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180509_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='userscoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_id', models.IntegerField(null=True)),
                ('element_id', models.IntegerField(null=True)),
                ('feat_priority', models.IntegerField(null=True)),
                ('feat_name', models.CharField(max_length=200, null=True)),
                ('mobile_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'User Score Record',
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'feature'},
        ),
        migrations.AlterModelOptions(
            name='sort_feature',
            options={'verbose_name_plural': 'Sort Feature'},
        ),
    ]
