# Generated by Django 2.0.5 on 2019-07-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190712_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='custom_exp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
