# Generated by Django 2.0.5 on 2018-07-03 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180703_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorerecord',
            name='date_modified',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
