# Generated by Django 2.0.5 on 2018-07-03 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_userscorerecord_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorerecord',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
