# Generated by Django 2.0.5 on 2019-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_experiment_feature_default_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_feature',
            name='default_levels',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
