# Generated by Django 2.0.5 on 2018-09-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_userscorerecord_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samsung_phone',
            old_name='price',
            new_name='price_in_pkr',
        ),
        migrations.AddField(
            model_name='samsung_phone',
            name='price_in_usd',
            field=models.IntegerField(null=True),
        ),
    ]
