# Generated by Django 2.0.5 on 2019-07-31 11:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190731_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_feature',
            name='default_levels',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=126, null=True, size=6),
        ),
    ]
