# Generated by Django 2.0.5 on 2019-01-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190109_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedadminphones',
            name='mob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mobilephones'),
        ),
    ]
