# Generated by Django 2.0.5 on 2018-10-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180910_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experiment_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_admin',
            field=models.BooleanField(default=False),
        ),
    ]
