# Generated by Django 2.0.5 on 2018-10-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20181001_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/img/frontDisplay/'),
        ),
    ]
