# Generated by Django 2.0.5 on 2019-07-31 16:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190731_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_feature',
            name='chosen_levels',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=126, null=True, size=6),
        ),
    ]
