# Generated by Django 2.0.5 on 2019-02-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190111_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilephones',
            old_name='back_camera',
            new_name='backcam',
        ),
    ]
