# Generated by Django 2.0.5 on 2019-02-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190212_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilephones',
            old_name='price_in_pkr',
            new_name='price',
        ),
    ]
