# Generated by Django 2.0.5 on 2019-07-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190731_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedadminphones',
            name='mob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.mobilephones'),
        ),
    ]
