# Generated by Django 2.0.5 on 2019-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190212_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedadminphones',
            name='batch_label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
