# Generated by Django 2.0.5 on 2018-10-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181001_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='price',
        ),
        migrations.AddField(
            model_name='phone',
            name='back_camera',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='imagepath1',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/img/sampleimages'),
        ),
        migrations.AddField(
            model_name='phone',
            name='imagepath2',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/img/sampleimages'),
        ),
        migrations.AddField(
            model_name='phone',
            name='price_in_pkr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price_in_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Chip',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Colors',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Cpu',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Dimensions',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Gpu',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Mobile_Companny',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Mobile_Name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='OS',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Resolution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Whats_new',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
