# Generated by Django 2.0.5 on 2019-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_selectedadminphones_batch_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort_feature',
            name='exp_sets',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
