# Generated by Django 2.0.5 on 2018-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20181001_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='imagepath1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imagepath2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
