# Generated by Django 2.0.5 on 2019-03-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_sort_feature_exp_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpCriteriaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cOrder_id', models.CharField(max_length=10, null=True)),
                ('pCriteria', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Block')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedadminphones',
            name='batch_label',
        ),
        migrations.AddField(
            model_name='selectedadminphones',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Block'),
        ),
        migrations.AddField(
            model_name='selectedadminphones',
            name='p_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selectedadminphones',
            name='pset_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
