# Generated by Django 2.0.5 on 2018-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20181001_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='imagepath1',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/img/sampleimages'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imagepath2',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/img/sampleimages'),
        ),
    ]
