# Generated by Django 2.0.5 on 2019-08-21 17:32

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_storecritweightlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_criteria_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuelist', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=210, null=True, size=10)),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.PhoneCriteria')),
            ],
        ),
    ]
