# Generated by Django 2.0.5 on 2019-03-11 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20190311_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedadminphones',
            name='exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
        migrations.AlterField(
            model_name='selectedadminphones',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
