# Generated by Django 2.0.5 on 2019-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_general_criteria_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_criteria_data',
            name='inputtype',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
