# Generated by Django 2.0.5 on 2019-08-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_general_criteria_data_inputtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='general_criteria_data',
            new_name='generalCriteriaData',
        ),
    ]
