# Generated by Django 2.0.5 on 2018-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20181001_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='prunedmobilephones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(null=True)),
                ('m_id', models.IntegerField(null=True)),
                ('roles', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Pruned Mobile Phones',
            },
        ),
    ]
