# Generated by Django 2.0.5 on 2019-03-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20190311_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expcriteriaorder',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Block'),
        ),
        migrations.AlterField(
            model_name='expcriteriaorder',
            name='exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
    ]
