# Generated by Django 2.0.5 on 2019-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20190312_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='expcriteriaorder',
            name='sh_hd',
            field=models.IntegerField(null=True),
        ),
    ]
