# Generated by Django 2.0.5 on 2019-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20190821_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephones',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
