# Generated by Django 2.0.5 on 2019-08-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20190823_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expcriteriaorder',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Block'),
        ),
        migrations.AlterField(
            model_name='expcriteriaorder',
            name='fvp',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
