# Generated by Django 2.0.5 on 2019-03-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_expcriteriaorder_sh_hd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedadminphones',
            name='mob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.mobilephones'),
        ),
    ]
