# Generated by Django 2.0.5 on 2018-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20181006_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
