# Generated by Django 2.0.5 on 2018-10-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_user_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='platform_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
