# Generated by Django 2.0.5 on 2019-04-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20190319_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='criteriaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpCriteriaOrderSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cOrder_id', models.CharField(max_length=10, null=True)),
                ('criteria', models.CharField(max_length=10, null=True)),
                ('pCriteria', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(null=True)),
                ('sh_hd', models.IntegerField(null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Block')),
                ('exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
        ),
    ]
