# Generated by Django 2.0.5 on 2019-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_criteriatable_expcriteriaorderset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='criteriaTable',
        ),
    ]
