# Generated by Django 2.0.5 on 2019-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_customexpsessiontable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexpsessiontable',
            name='cusexpid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
