# Generated by Django 2.0.5 on 2019-04-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20190405_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecriteria',
            name='priority',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
