# Generated by Django 2.0.5 on 2019-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_customexpsessiontable_cusexpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexpsessiontable',
            name='cusexpid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
