# Generated by Django 2.0.5 on 2018-10-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20181006_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
