# Generated by Django 2.0.5 on 2018-10-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20181006_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Role'},
        ),
    ]
