# Generated by Django 2.0.5 on 2019-09-18 23:24

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20190908_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='surveyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveydata', django_mysql.models.ListCharField(models.CharField(max_length=30), blank=True, max_length=400, null=True, size=10)),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
        ),
    ]
