# Generated by Django 2.0.5 on 2019-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_phonecriteria_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecriteria',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
