# Generated by Django 2.0.5 on 2019-04-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_phonecriteria_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='expcriteriaorder',
            name='fvp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
