# Generated by Django 2.0.5 on 2018-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20181006_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
