# Generated by Django 2.0.5 on 2018-10-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20181006_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform_feature',
            options={'verbose_name_plural': 'platform_feature'},
        ),
    ]
