# Generated by Django 2.0.5 on 2019-05-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20190412_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecriteria',
            options={'verbose_name_plural': 'Phone Criteria'},
        ),
    ]
