# Generated by Django 2.0.5 on 2018-10-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20181006_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='template_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_del', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='template_roles',
            name='template_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.templates'),
        ),
    ]
