# Generated by Django 2.0.5 on 2018-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20181009_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='template_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
