# Generated by Django 2.0.5 on 2018-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20181009_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='userroles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrole', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='template_roles',
            options={'verbose_name_plural': 'Template Roles'},
        ),
        migrations.AlterModelOptions(
            name='templates',
            options={'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='template_roles',
            name='can_add',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='template_roles',
            name='can_del',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='template_roles',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='template_roles',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
