# Generated by Django 2.0.5 on 2018-10-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_platform_feature_subdetails'),
        ('webapp', '0029_experiment_feature_set'),
    ]

    operations = [
    ]
