# Generated by Django 2.0.5 on 2018-10-15 12:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_platform_feature_subdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_feature',
            name='subdetails',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=126, null=True, size=6),
        ),
    ]
