# Generated by Django 2.0.5 on 2018-10-16 10:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_merge_20181016_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_feature',
            name='subdetails',
        ),
        migrations.AddField(
            model_name='platform_feature',
            name='feature_levels',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=126, null=True, size=6),
        ),
    ]
