# Generated by Django 2.0.5 on 2018-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20181016_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='custom_exp_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='platform_feature',
            name='feature_symbol',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
