# Generated by Django 2.0.5 on 2018-10-17 10:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20181016_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='feature_set',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, null=True, size=100),
        ),
    ]
