# Generated by Django 2.1.2 on 2018-10-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_block_experiment_feature'),
        ('webapp', '0033_auto_20181017_0322'),
    ]

    operations = [
    ]
