# Generated by Django 2.1.2 on 2018-10-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_merge_20181019_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment_Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='feature_set',
        ),
        migrations.AddField(
            model_name='experiment',
            name='batches_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='capacity',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='status',
            field=models.CharField(default='DESIGN_MODE', max_length=100),
        ),
        migrations.AddField(
            model_name='experiment_batch',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment'),
        ),
    ]
