# Generated by Django 2.1.2 on 2018-10-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20181019_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_feature',
            old_name='feature_id',
            new_name='p_feature',
        ),
    ]
