# Generated by Django 2.1.2 on 2018-10-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_auto_20181024_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Block'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
