"""
Django settings for biasweb project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#nve)401#b-vm9+g$06zvc%ozu6^a78za+6+b9g$(%@-_4en^u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['172.16.22.79']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
    'crispy_forms',
    
    'jquery_ui',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biasweb.urls'

TEMPLATES = [
    
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': ['./templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    
]

WSGI_APPLICATION = 'biasweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'django_biasweb10',
         'USER':'root',
         'PASSWORD':'Opensesame1',
         'HOST': '127.0.0.1',
         'PORT':'3306',
     }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#
#Static url is to add url to the static files location. 
# This will render like this: https://static/example.js

STATIC_URL = '/static/'
# telling django to use the extend user model webappuser
AUTH_USER_MODEL = 'webapp.User'
# After successfull login the user will be redirected to the homepage.
LOGIN_REDIRECT_URL = 'homepage'
# After the user will logout he will be redirected back to the login page. 
LOGOUT_REDIRECT_URL = '/accounts/login/'
#-------------------------------------------------------------------------
# All these settings are done for the password resset purpose. 
# According to these settings the email will be send to the user who forgot his password. 

EMAIL_HOST = 'smtp.gmail.com'   # We are telling to use smtp host of google 
EMAIL_PORT = 587                # if we are using TLSthen we require 587 port number
EMAIL_HOST_USER = 'mudabirahmad1994@gmail.com'  # This will be the email address of the user 
                                                #from whome the email will be sent to others
EMAIL_HOST_PASSWORD = 'Fccgrad2'                # host password
EMAIL_USE_TLS = True            
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" # we are telling django to use smtp 
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails") # This is the path where all emails sent to different users will be saved.
DEFAULT_FROM_EMAIL = 'mudabirahmad1994@gmail.com' # email id
EMAIL_USE_LOCALTIME=True                         # 